
#ifndef __Predator_hxx__
#define __Predator_hxx__

#include <Agent.hxx>
#include <Action.hxx>

#include <string>

namespace Examples
{

class Predator : public Engine::Agent
{

	int _maxPredatorHuntDistance; // MpiBasicAttribute: maximum distance for the predator to hunt

public:
	// creates a Predator agent
	Predator(const std::string & id, const int& maxPredatorHuntDistance);
	// destroys a Predator agent
	virtual ~Predator();

	// Getter for the _maxPredatorHuntDistance class attribute
	int getPredatorHuntDistance() const;

	// selects wich actions and in wich order each Predator agent
	void selectActions();
	
	void updateState( );
	void updateKnowledge( );


	///// Autogenerated code (do not modify): /////
	Predator( void * );
	void* fillPackage() const;
	void freePackage(void* package) const override;
	bool hasTheSameAttributes(const Engine::Agent& other) const override;
	void sendVectorAttributes(int);
	void receiveVectorAttributes(int);
	void* createComplexAttributesDeltaPackage(int& sizeOfPackage) const override;
	void copyContinuousValuesToDiscreteOnes() override;
	///////// End of autogenerated code ///////////


	///// Autogenerated code (do not modify): /////
private:
	int _discrete_maxPredatorHuntDistance;

	///////// End of autogenerated code ///////////


	///// Autogenerated code (do not modify): /////
private:
	std::vector<std::tuple<int, int, float>> _deltaFor_hey1;			// <typeOfModification, elementIndex, elementNewValue>
	std::vector<std::tuple<int, bool>> _deltaFor_hey2;			// <typeOfModification, elementNewValue>
	std::vector<std::tuple<int, int, Engine::Point2D<int>>> _deltaFor_hey3;			// <typeOfModification, elementKey, elementValue>

	void insertElementAtIndex_hey1(const float& element, const int& index);
	void updateElementAtIndex_hey1(const float& element, const int& index);
	void deleteElementAtIndex_hey1(const int& index);
	void pushElement_hey2(const bool& element);
	void popElement_hey2();
	void insertOrUpdateElement_hey3(const int& key, const Engine::Point2D<int>& value);
	void deleteElement_hey3(const int& key);
	///////// End of autogenerated code ///////////

};

} // namespace Examples

#endif // __RandomAgent_hxx__
